### ISSUE TITLE
Change conditionPrincipleDiagnosis to conditionRoleIsBilling

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/CsvToFHIR#13]
The FHIR specification advises that "the advice was to define Principal Diagnosis by constraining Encounter.diagnosis.role to "Billing Diagnosis" and requiring Encounter.diagnosis.rank =1."
Source:  https://jira.hl7.org/browse/FHIR-15944

The model and processing should reflect this guidance.

- [x] change Condition/model from three effectively boolean values (  conditionPrincipalDiagnosis
conditionRoleIsAdmitting & 
conditionRoleIsChiefComplaint) to a single conditionDiagnosisUse, which has possible values:  AD, DD, CC, CM, pre-op, post-op, and billing.  (See https://terminology.hl7.org/3.1.0/CodeSystem-diagnosis-role.html)
- [x] Add display names for these values in fhir_constants.EncounterResource
- [x] Create processing in Condition/ffhirs based on the conditionDiagnosisUse
- [x] Remove decoration of use code + Id.  Use the straight ID

**Comment by cragun47** [comment]
Completed in PR: https://github.com/LinuxForHealth/CsvToFHIR/pull/17

**Comment by klwhaley** [comment]
Included in release 1.1.0 https://github.com/LinuxForHealth/CsvToFHIR/releases/tag/1.1.0
