### ISSUE TITLE
MedicationAdministration should not override a value set as medicationUseStatus

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/CsvToFHIR#20]
Currently if MedicationAdministration does not have a medicationUseOccuranceDateTime, then the medicationUseStatus is overridden to unknown.  If the use status is provided, it should be retained.   
medicationUseOccuranceDateTime will cause a MedicationStatement to be created and it defaults to "unknown" if a medicationUseStatus is not provided.   Thus a default is already accounted for.  

Change code so if a medicationUseStatus is provided, it is retained.

**Comment by cragun47** [comment]
@LisaWellman FYI.

**Comment by klwhaley** [comment]
Included in release 1.1.0 https://github.com/LinuxForHealth/CsvToFHIR/releases/tag/1.1.0
