### ISSUE TITLE
Update to FHIR Ethnicity System

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/CsvToFHIR#22]
Change the supported Ethnicity System from v2 system : http://terminology.hl7.org/CodeSystem/v2-0189 to v3 system : https://terminology.hl7.org/3.1.0/CodeSystem-v3-Ethnicity.html. Update associated constants, tests, and documentation.

**Comment by klwhaley** [comment]
Included in release 1.1.0 https://github.com/LinuxForHealth/CsvToFHIR/releases/tag/1.1.0
