### ISSUE TITLE
Add function to perform just the transformation

### ISSUE THREAD

**Issue by hammadk373** [LinuxForHealth/CsvToFHIR#30]
Currently the converter only works when converting the contents of the CSV to FHIR resources. The dataframe transformation/normalization logic is very powerful and useful on its own. We would benefit from utilizing this transformation logic to convert to other arbitrary data models.

**Comment by klwhaley** [comment]
Reopening until we cut a full release with this in it.

**Comment by klwhaley** [comment]
Included in release 1.1.0 https://github.com/LinuxForHealth/CsvToFHIR/releases/tag/1.1.0
