### ISSUE TITLE
Support passing additional parameters to pandas

### ISSUE THREAD

**Issue by hammadk373** [LinuxForHealth/CsvToFHIR#32]
Add support for passing in additional parameters to the pandas read_* functions. An example of a use case is where we want to skip some rows in the csv file. Pandas supports `skiprows` parameter for the read_csv function. We can use this new functionality to pass these kinds of configuration that not directly supported by the CsvToFHIR data contract.

**Comment by klwhaley** [comment]
Included in v1.2b0 
https://github.com/LinuxForHealth/CsvToFHIR/releases/tag/v1.2b0
